baseurl = "https://dropleafgames.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Drop Leaf Games"
theme = "hugo-theme-dream"

# copyright = "2021"

# googleAnalytics = "G-VMZ9SRBL9X"

# disqusShortname = "drop-leaf-games"

# enableRobotsTXT = true

[params]
  background = "#f7f7f7"
  backgroundImage = "/img/background.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  author = "Bryce Castor"
  # description = ""
  avatar = "/img/avatar.png"
  # headerTitle = ""
  motto = "Embrace minimalism and versatility in board games to play more with less."
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "bryce.castor@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

  favicon = "img/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJS = []
